### PR TITLE
Create 404.html

### LINKED ISSUE #21: Create a 404 page

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #21. This simply redirects to homepage.

### CODE REVIEW

**Comment by astorije** [comment]
I'd prefer to have a real 404 page rather than a redirect (`up for grabs` 😉), but I'll go with the flow if other maintainers prefer to have this.

**Comment by MaxLeiter** [comment]
@thelounge/maintainers quick second :+1:?

**Comment by maxpoulin64** [comment]
I agree with @astorije here. At this point might as well just redirect on the server-side without displaying a page as well. This one is hardly more helpful than just having the server error out.

**Comment by astorije** [comment]
Closing in favor of #40.

**Pull request closed without merging**
