### PR TITLE
Updated styleguide files with new icon

### PR DESCRIPTION
**Pull request by Mandihamza**
Task via #79

### CODE REVIEW

**Comment by astorije** [comment]
Whoa, you actually did it! 👏

One thing I noticed though is that the font between [this PR's version](https://github.com/Mandihamza/thelounge.github.io/blob/update-style-guide/assets/logos/The_Lounge_Brand_Guidelines/The_Lounge_Brand_Guidelines.pdf) and [the `master` version](https://github.com/thelounge/thelounge.github.io/blob/master/assets/logos/The_Lounge_Brand_Guidelines/The_Lounge_Brand_Guidelines.pdf) changed. Or maybe just the boldness.
Would you mind looking into this? Sorry for the extra work! 🙏

**Comment by Mandihamza** [comment]
Hey @astorije all fixed up!

**Comment by astorije** [comment]
Thanks a bunch @Mandihamza!!

Seeing you're one of our contributors, you are more than welcome to request a sticker pack [here](https://goo.gl/forms/f5usqAEp5DWoeXC92), if you want. I'll ship them to you as soon as I can :)

**Comment by Mandihamza** [comment]
Awesome, I requested some stickers @astorije! Can't wait to see them 💥

**Pull request merged**
