### PR TITLE
Align footer button with the text, remove deprecated iframe attributes

### PR DESCRIPTION
**Pull request by xPaw**

### CODE REVIEW

**Comment by astorije** [comment]
Do you know what's up with the font?

PR | Master
screen shot 2018-11-05 at 23 08 12 | screen shot 2018-11-05 at 23 08 19

I'd keep the contributors part out of it though 🤷‍♂️ 
Also, do we have any control on the 2k vs. 2220 number? We're not that popular lol, "2k" is a bit too rounded imo.

**Comment by xPaw** [comment]
> I'd keep the contributors part out of it though 🤷‍♂️

I think it's an interesting metric to display. For example Shout has almost double our stars, and more than double less contributors :)

> Also, do we have any control on the 2k vs. 2220 number?

Sadly we don't, but there's a couple of issues on shields.io to display thousands.

> Do you know what's up with the font?

Dunno, looks fine on my end.

**Comment by xPaw** [comment]
@astorije I reverted to iframe, let's at least merge css fixes.

**Comment by astorije** [comment]
Thanks!

**Pull request merged**
