### PR TITLE
Add a FAQ section + why forking?

### PR DESCRIPTION
**Pull request by almet**

### CODE REVIEW

**Comment by astorije** [comment]
I'm not too sure a FAQ section belongs to the website just yet, especially considering this section will only contain one entry.
If building a proper FAQ, https://github.com/thelounge/lounge/wiki is probably a better place until it gets some content and directions.

However, the website should definitely mention something as said in #4. @almet, what do you think about a sixth entry in [the homepage](https://thelounge.github.io/) instead, under "Why you should use it"? Something along the lines of:

> The Fellowship of The Lounge [lol, I didn't have any better, it's late]
> The Lounge is a community-run spin-off of Shout, managed by a dedicated team [...]

Including a link to the anchor in the README of the `lounge` repo, or to the potential FAQ wiki page if we end up creating one.

**Comment by almet** [comment]
sure! If you feel it's too early for a FAQ then let's just add a mention and a link to the README item.

**Comment by astorije** [comment]
@almet, OK to close this PR and open a new one with that change (to keep archive)?

**Comment by JocelynDelalande** [comment]
I'd  agree with @almet original proposal : the github wiki is really targeted to advanced-users, if not developers… (reminder: home page of github project is a code tree).

Such an high-level question can belong to the website, IMHO.

(but it could include a link to https://github.com/thelounge/lounge/wiki/Differences-between-The-Lounge-and-Shout, which is more technical stuff)

**Comment by astorije** [comment]
@JocelynDelalande, if you read carefully, the proposal ended up to be:

> However, the website should definitely mention something as said in #4. @almet, what do you think about a sixth entry in the homepage instead, under "Why you should use it"? Something along the lines of:
> [...]
> Including a link to the anchor in the README of the lounge repo, [...]

This would appear here, on the homepage:

screen shot 2016-03-06 at 12 20 11

Having a FAQ page just for the sake of having a FAQ page, with just one entry, is just a no-go for me. Having that information on the homepage seems much more sensible.
(Also, FAQ pages are usually very unintuitive for the reader, as they are the pot pourri of things you don't know where to put)

**Comment by almet** [comment]
I disagree with the fact that FAQ is a "pot-pourri". To me it's a set of answers to the questions that are commonly asked. Such as "why forking shout?" or "How does this compare to glowing bear" for instance.

That being said, I don't have any strong opinion about where to put this piece of information. Having it on the landing page seems a bit weird to me since the fact it's a fork is not a reason why I would use it.

**Comment by astorije** [comment]
> Having it on the landing page seems a bit weird to me since the fact it's a fork is not a reason why I would use it.

No, but being under active-development with an established community is, IMO. Frankly, it outweighs the fact that we would have one single entry in the FAQ. If you can think of other questions that need answering, and unless these questions belong to better sections, then sure, we could think of a FAQ entry...

**Comment by JocelynDelalande** [comment]
I agree with what @almet expressed on FAQs (+ FAQ is good cause you can point people to it via URL when the question is asked on IRC for eg). But it is not a strong opinion, and I'd prefer seeing it on the landing page rather than lost inside the wiki.

**Comment by almet** [comment]
Superseded by #12

**Pull request closed without merging**
