### PR TITLE
Add DO deployment document

### PR DESCRIPTION
**Pull request by jessebolson**

### CODE REVIEW

**Comment by YaManicKill** [comment]
I'm not a fan of this. We have previously said that we won't have docs for stuff like node which have decent docs on installing themselves, we already have docs on using nginx, and this is definitely not specific to digital ocean. I'm not sure what other maintainers think.

**Comment by jessebolson** [comment]
> We have previously said that we won't have docs for stuff like node which have decent docs on installing themselves

Understood, I was not aware of this. 

> and this is definitely not specific to digital ocean

Correct, I didn't know what to call it (generic server installation guide?) - having systemd files in place + a system user + a reverse proxy is something that I think would help ease people into setting the product up. Not that the documentation doesn't exist, but having it in one place would've been helpful for me at least.

> we already have docs on using nginx

Do you think a better PR would be getting that documentation into the doc site?

**Comment by YaManicKill** [comment]
> Not that the documentation doesn't exist, but having it in one place would've been helpful for me at least.

The problem is, how many permutations of different options do we create? I get this point, but we can't spend forever writing different permutations just to make it easier.

> Do you think a better PR would be getting that documentation into the doc site?

Possibly. At this point I'll tag in @astorije because I know he has been updating the docs slowly and I'm not sure if this is included.

We should probably get those up sometime soon.

**Comment by xPaw** [comment]
This feels like a piece that could be on https://www.digitalocean.com/community/tutorials 

I agree with @YaManicKill here.

**Comment by jessebolson** [comment]
> I get this point, but we can't spend forever writing different permutations just to make it easier.

Gotcha.

> Possibly. At this point I'll tag in @astorije because I know he has been updating the docs slowly and I'm not sure if this is included.

Agreed - at least having system users + reverse proxying in the same place would be useful, even if they're just links to external resources.

**Comment by astorije** [comment]
> Possibly. At this point I'll tag in @astorije because I know he has been updating the docs slowly and I'm not sure if this is included.

So in the new docs I'm building (planning to resume work on this soon), there will be the official guides, and then unofficial guides and/or links to external guides. In the meantime, I suggest using our wiki for that, and when something reaches a good quality, it could be moved to unofficial guides. It'll be clearer when I show progress for the docs.

Or even better like @xPaw said:

> This feels like a piece that could be on https://www.digitalocean.com/community/tutorials

Either way, I don't think we should include this in the current docs. Thanks for your efforts though, and feel free to add that to the [community wiki](https://github.com/thelounge/lounge/wiki) for now, or to the DO tutorials.

**Comment by jessebolson** [comment]
DO tutorials seems like a great place for this, maybe it'll throw some exposure your way, and it satisfies my desire to have all of this in one place. Feel free to close, thanks!

**Comment by astorije** [comment]
Thanks for this, @jessebolson! :)

**Pull request closed without merging**
