### PR TITLE
Updated install documentation

### PR DESCRIPTION
**Pull request by dzek69**
Added installation steps for Debian-based OS-es with no root access. I've been running Shout/The Lounge this way for months.

### CODE REVIEW

**Comment by spangborn** [comment]
You could also include just adding `.node_modules/.bin` to your path instead of having to execute the full path.

**Comment by williamboman** [comment]
Even easier would be to install a node version manager such as nvm or n and install The Lounge globally in your home directory.

**Comment by YaManicKill** [comment]
Once #49 has been merged, could you update this, @dzek69 to just be at the end and distro-non-specific header. It'll be useful for people who want to run without root, but it isn't specific to debian based OS.

Also, jsut fwiw, there's an easier way to do global installs without root: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

So maybe it's worth checking this to see if it works for you before updating it?

**Comment by astorije** [comment]
Sorry to be that guy, but is this something we want to document though? I feel like this is a fairly non-standard environment and, in general, I don't remember seeing many projects documenting how to install services like this on systems they do not control.

Something that concerns me is that, since person is lacking control over the environment, who knows how it's configured? If Node is missing or wrong version, it needs an extra step than just `npm install` (though this can be fixed by solutions from @YaManicKill and @williamboman above, it means we either think of all/most cases or we make assumptions), there may be a firewall blocking ports by default, etc.

Anyway, definitely not a 👎 but a genuine concern and question as I think official documentation should not make assumptions or take unusual routes, but I'm open for discussion of course.

**Comment by YaManicKill** [comment]
> Sorry to be that guy, but is this something we want to document though?

I mean, you have a legitimate point, but I think it would be good to at least have a comment somewhere in the instructions that mentions there is a way to install it without root if you have to.

Most people won't assume this is possible and just assume they can't run it themselves.

**Comment by astorije** [comment]
> I think it would be good to at least have a comment somewhere in the instructions that mentions there is a way to install it without root if you have to.
> 
> Most people won't assume this is possible and just assume they can't run it themselves.

I agree. I think for now, [this page in the wiki](https://github.com/thelounge/lounge/wiki/Alternative-Install-methods) is the most appropriate way to do so.
In a short future however (as I'm starting to think about better documentation), we should have a page that documents "Unofficial install methods" and this plus everything else in this wiki page that is not part of the official install methods (i.e. regular `npm install -g`, using the `.deb`, using the `.aur`, using Docker). This page would have a warning at the top saying that unofficial means it might not work in 100% configurations and they are not being maintained by team members.

@YaManicKill, what do you think we put the content of this PR into the wiki page, **for now**?

**Comment by YaManicKill** [comment]
Yeah, I'm alright with that.

**Comment by xPaw** [comment]
The new documentation (#84) is much more verbose in the installation process, so I'm gonna close this PR. Sorry it took so long.

**Pull request closed without merging**
