### PR TITLE
docs: Add LDAP fields

### LINKED ISSUE #145: Write page "How to set up LDAP authentication for The Lounge"

### PR DESCRIPTION
**Pull request by gramakri**
Fixes #145

### CODE REVIEW

**Comment by xPaw** [comment]
This effectively just listed the options that are on config page as well.

I think this guide should show some examples instead.

**Comment by xPaw** [comment]
I suppose they provide some common configuration examples, I haven't used LDAP so I don't know how much sense they actually make.

If you think such examples are reasonable, I wouldn't mind seeing these with lounge's config then.

**Comment by gramakri** [comment]
Yeah, with LDAP there is no such thing as a common configuration. All the values in the fields depend entirely on the LDAP server setup and there is no 'standard'. A poor analogy is to think of the LDAP server as a sort of XML document and each LDAP admin comes up with their own XML tags and hierarchy. They then fill up these tags in the LDAP configuration of an app (sort of like XPath/XQuery paths).

That said, if it helps I can update the PR to have the actual values we use for the Cloudron setup.

**Comment by xPaw** [comment]
> That said, if it helps I can update the PR to have the actual values we use for the Cloudron setup.

That sounds like a good idea (show the entire config as a json object) and some explanation on top of it.

**Comment by astorije** [comment]
Agreed, some context would be nice. Thanks a ton for your help @gramakri, highly appreciated!

I have not used LDAP much either, so I'm not sure what to expect as a reader as well.

@vivienlacourba, if you are still planning to set up The Lounge, what would you expect in a documentation describing how to set up LDAP for The Lounge?
The current guide is [a work in progress here](https://deploy-preview-179--thelounge.netlify.com/docs/guides/ldap). Feel free to ping me on Freenode if you need some context to answer this question 😅

**Comment by Gorian** [comment]
> Yeah, with LDAP there is no such thing as a common configuration. All the values in the fields depend entirely on the LDAP server setup and there is no 'standard'. A poor analogy is to think of the LDAP server as a sort of XML document and each LDAP admin comes up with their own XML tags and hierarchy. They then fill up these tags in the LDAP configuration of an app (sort of like XPath/XQuery paths).
> 
> That said, if it helps I can update the PR to have the actual values we use for the Cloudron setup.

This isn't entirely accurate - Active Directory is the most common LDAP in use, and comes out of the box setup with defaults, many of which are sane. While most admins while put users in a different OU than default, many things will stay default, like the User Login being "sAMAccountName", which makes it a sane default for `primaryKey` in the config for about 90%+ of AD installs.

**Comment by astorije** [comment]
@gramakri, are you still planning on improving this guide? @Gorian, wanna help writing it? Thanks, all!

**Pull request closed without merging**
