### PR TITLE
Adds demo link

### PR DESCRIPTION
**Pull request by MaxLeiter**

### CODE REVIEW

**Comment by astorije** [comment]
:+1: 

We'll want to have a nicer demo as the userbase scales, but for now it's all good IMO. @MaxLeiter, did you find something in the code that offers to lock to a single IRC server like http://demo.shout-irc.com/ does or is it a local change just for the demo not in the codebase?

@JocelynD or @YaManicKill, care to give your :+1: and merge? FYI it was one of the things the Freenode staff asked us to claim the channel :-)

**Comment by MaxLeiter** [comment]
I just added the 'disabled' tag in HTML @astorije

**Comment by astorije** [comment]
Nice!

**Comment by YaManicKill** [comment]
Yeah, :+1: from me. Thanks for this, @MaxLeiter

**Comment by xPaw** [comment]
> I just added the 'disabled' tag in HTML @astorije

While we're at it, why not turn it into an option? An option that allows the admin to lock the server.

**Comment by astorije** [comment]
Yes, something in the admin's configuration file would be very useful, I think, and not only for a demo!
Open an issue on https://github.com/thelounge/lounge and we'll discuss the possibilities :-)

**Pull request merged**
