### PR TITLE
Add all assets related to the logos

### PR DESCRIPTION
**Pull request by astorije**
These were uploaded in the exact format, hierarchy, extensions, filenames, etc. as provided by the artist. It is customary to keep it that way in cases there needs to be adjustments to be discussed and made with the original artist (except it is usually not in a git repo, but considering the OSS nature of the project, website repo makes a lot of sense for this).

It's a lot of files, but it only weighs 13MB, and it's not a repo necessary to run the project or whatnot, I don't expect a lot of people outside the core team to clone this repo.

README makes the guidelines visible when browsing in the folder on GitHub: https://github.com/thelounge/thelounge.github.io/tree/astorije/logos/assets

### CODE REVIEW

**Comment by xPaw** [comment]
Do we need font files in the repo? It's not hard to find it if needed.

**Comment by astorije** [comment]
I'd like to keep them yes. It doesn't hurt at all to have them (it's only 1.4MB combined), and they're required to open the AI files. And I've been in situations where you don't have the exact same font as the one used to make the files, and that messes up.

**Comment by astorije** [comment]
FYI, I have used one of the SVG files from here to generate the PNG logo (with correct dimensions, centering, etc.) at https://github.com/github/explore/pull/156. If we ever need to do that again, here is the diff:

```diff
$ git diff
─────────────────────────────────────────────────────────────────────────────────────────
modified: assets/logos/logo/TL_Grey&Yellow_Logo_White_Bg/TL_Grey&Yellow_Logo_White_Bg.svg
─────────────────────────────────────────────────────────────────────────────────────────
@ TL_Grey&Yellow_Logo_White_Bg.svg:4 @
 <?xml version="1.0" encoding="utf-8"?>
 <!-- Generator: Adobe Illustrator 22.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
-<svg version="1.1" id="Livello_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
-    viewBox="0 0 386 276" style="enable-background:new 0 0 386 276;" xml:space="preserve">
+<svg width="288" height="288" version="1.1" id="Livello_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
+    viewBox="0 0 336 336" style="enable-background:new 0 0 336 336;" xml:space="preserve">
 <style type="text/css">
-   .st0{fill:#FFFFFF;}
+   .st0{fill:transparent;}
    .st1{fill:#FF9E18;}
    .st2{fill:#415364;}
 </style>
 <g>
-   <rect class="st0" width="386" height="276"/>
+   <rect class="st0" width="336" height="336"/>
 </g>
 <g>
    <g>
-       <g>
+       <g transform="translate(-25,30)">
            <g>
                <path class="st1" d="M320.1,100l0,76.1c0,0.7-0.4,1.3-0.9,1.6l-65.8,37.7c-0.6,0.3-1.3,0.3-1.8,0l-66.1-38
                    c-0.6-0.3-0.9-0.9-0.9-1.6l0-66.8c0-0.7-0.4-1.3-0.9-1.6L165.5,97c-1.2-0.7-2.8,0.2-2.8,1.6v84.5c0,3.9,2.1,7.6,5.5,9.5
```

**Comment by xPaw** [comment]
Sure

**Pull request merged**
