### PR TITLE
Use SVG logos for app stores

### PR DESCRIPTION
**Pull request by xPaw**

### CODE REVIEW

**Comment by astorije** [comment]
For some reason, the Franz SVG is super pixellated 😕

[Master](https://next.thelounge.chat/docs/install-and-upgrade#services-packaging-the-lounge) | [This PR](https://deploy-preview-166--thelounge.netlify.com/docs/install-and-upgrade)
--- | ---
 | 

These screenshots were taken on my phone, it seems okay on laptop.

**Comment by xPaw** [comment]
@astorije I think I fixed it.

**Comment by astorije** [comment]
Looks like it. What that the shadow? Is it part of their official logo that we're altering by removing it?

**Comment by xPaw** [comment]
I removed the shadow to fix the image overflowing outside the container (in the svg itself), and it doesn't look like it's part of the logo if you look around their site.

It also looks more balanced when displaying next to other logos.

**Comment by astorije** [comment]
> it doesn't look like it's part of the logo if you look around their site.

I'm not sure about this: on their website and GitHub repo, their logo (the logo itself, not modified ones such as the square app icon, etc.) always has this ring with shadow.

However, I totally agree with you that it fits better like this on our website. If they are upset about this, they can always come ask us to use another version that doesn't have the bug, and we can remind them to use our official logo on their website ;)

**Pull request merged**
