### PR TITLE
Use querySelector instead of getElementById

### PR DESCRIPTION
**Pull request by astorije**

### CODE REVIEW

**Comment by xPaw** [comment]
:-1::laughing: It's totally slower

**Comment by astorije** [comment]
Should we benchmark this? I think this is critical piece of software.

**Comment by astorije** [comment]
ALRIGHT ALRIGHT WHATEVER.

**Comment by xPaw** [comment]
We should also get :+1: from every maintainer before merging a change that affects performance critical places.

**Comment by maxpoulin64** [comment]
I know you like querySelector @astorije, but I agree with @xPaw it's totally overkill and unnecessary.

**Pull request closed without merging**
